name: Update CloudFormation Stack

on:
  push:
    paths:
      - 'IAC/**'

jobs:
  update-stack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update CloudFormation Stack
      run: |
        aws cloudformation update-stack --stack-name <nombre-de-tu-stack> --template-body file://IAC/infrastructure.yaml --parameters ParameterKey=GithubOauthToken,ParameterValue=$REPOSITORY_TOKEN --capabilities CAPABILITY_NAMED_IAM
      env:
        REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
